version: '2'

services:
  mariadb:
    image: ${IMAGE_MARIADB} # 本番環境
    # image: bitnami/mariadb:10.6 # 開発環境
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      # - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=${DB_USERNAME}
      - MARIADB_DATABASE=${DB_DATABASE}
      - MARIADB_PASSWORD=${DB_PASSWORD}
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}

  myapp:
    tty: true
    image: ${IMAGE_LARAVEL} # 本番環境
    # image: bitnami/laravel:8 # 開発環境
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USERNAME=${DB_USERNAME}
      - DB_DATABASE=${DB_DATABASE}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - mariadb
    ports:
      - 80:3000
    volumes:
      - ./:/app
    # privileged: true # Privileged mode could be required to run this container under Windows
